# Generated by Django 5.2 on 2025-04-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('ville_depart', models.CharField(max_length=120)),
                ('latitude_depart', models.FloatField()),
                ('longitude_depart', models.FloatField()),
                ('nb_places', models.PositiveSmallIntegerField(default=3)),
                ('heure_depart', models.TimeField()),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducteurs', to='frontend.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('ville_depart', models.CharField(max_length=120)),
                ('latitude_depart', models.FloatField()),
                ('longitude_depart', models.FloatField()),
                ('heure_souhaitee', models.TimeField()),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagers', to='frontend.evenement')),
            ],
        ),
    ]
